### PR TITLE
[INT-525] fetch error when using forceComplete endpoint 

### PR DESCRIPTION
**Pull request by YokySantiago**
**Fixed**

- forceComplete endpoint doesn’t provide a response body so it was throwing an fetch error

### CODE REVIEW

**Review by jcpmmx — APPROVED** [review]
LGTM!

Nitpicking, I'd make it a one-liner:
```js
if (operations === 'DELETE') return res.status;
return res.json().catch(() => res.status);
```

**Comment by jamesliupenn** [comment]
I think I've intentionally kept the curly braces throughout the code-base due to the fact that simplification isn't always great: https://javascript.info/coding-style#curly-braces 

I would kindly suggest use the more readable format here ;)

**Review by jcpmmx — APPROVED** [review]
LGTM!

**Comment by YokySantiago** [comment]
Release version: v1.2.10

**Pull request merged**
