### PR TITLE
Add end point: getWorkerEta

### PR DESCRIPTION
**Pull request by cctv1237**
Just need to use this end point and cannot wait.

### CODE REVIEW

**Comment by jamesliupenn** [comment]
LGTM, I'll merge this and publish to npm first thing tomorrow :)

**Comment by cctv1237** [comment]
> LGTM, I'll merge this and publish to npm first thing tomorrow :)

Cheers mate

**Comment by jamesliupenn** [comment]
> > LGTM, I'll merge this and publish to npm first thing tomorrow :)
> 
> Cheers mate

Thanks for the contribution!

**Comment by cctv1237** [comment]
> > > LGTM, I'll merge this and publish to npm first thing tomorrow :)
> > 
> > 
> > Cheers mate
> 
> Thanks for the contribution!

Btw, maybe need to inform the guy who's maintaining the Typescript @types for this repo to do some updates

**Review by jamesliupenn — APPROVED** [review]
LGTM, thanks for adding in the test modules

**Pull request merged**
